travis:
  secure:
    BINSTAR_TOKEN: cdCnEYJ0oZ0+xG4CmJdpqUkzykcfHG3cyiUMiBUvVjgTvZqWMcroeqkJgCI3R3lvxxB6amuj1L/Kvu0uBwWives/Eq+s/jpPgwGeP5zA0f7gMSFKqHnst5X+qWpqAvKdiKdgtHgAW8V25ptrj5djGZDmyq0hewqxzRdl8D+aaNuS126JxyEflHGOJZbywH/fXg7cV+gCpcK1NpECrYNSnruZrGVwEsGx2qXUd0ObEQ4j5LUDFHyeTtzATQjVejO8yyKa23UX8R4PVt8d5gp8zdLBgm9TZA+F3XKzVNr638+sOik6hSt/kPfRbJGNgWkn5X+DimR9PBvVHUjiaTPp5SoM9z5gNsfl8MvW9ansqdCgna5yd0eFIfdYXlUC7MI+jsdt4lxgXw76+UCViTqh5oVDB+FK9J28cchKGe18Yp3ksm4wHaAAEMVrLiioHPxfvwaxGF/FHm0zgcvJPXOebH42jIuQC9njEV921prCHBk33bo2slhGq/+cKR0ToA9I0YZWsDkL4+SDT2iFTHYnPJ66/iRkbjiUN6tNdNTLDoH27i1IJ38WcsCgd8UtU44TSIAzbCsLcQzi0lgoChjeLGUguabuoaDi8gaZS85FMgH32P0+yeOlzWcbqKCbZ3LwPIoGp/JuQ9/qpGTSPW8/DdDtrB7R8AqrnzCC8+v1i24=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
